#!/usr/bin/env bash

DOSBOX=dosbox
PMDNAME=$(basename $0)

declare -a COMMANDS_LIST=(
  compile shell play
)
declare -A COMMANDS_MAP
for key in ${!COMMANDS_LIST[@]}; do
  COMMANDS_MAP[${COMMANDS_LIST[${key}]}]=${key}
done

usage() {
  echo "${PMDNAME}: [${COMMANDS_LIST[*]}] ..." >&2
}

if [ $# -lt 1 ]; then
  usage
  exit 1
elif [ -z "${COMMANDS_MAP[$1]}" ]; then
  usage
  echo "Unknown command: $1" >&2
  exit 1
fi

PMDCMD="$1"
shift 1

dosbox_init() {
  if [ -n "${PROJMD_DBINIT}" ]; then
    echo "Error: Calling dosbox_init with PROJMD_DBINIT still defined!" >&2
    exit 1
  fi
  export PROJMD_DBINIT=$(mktemp dosbox_init.conf.XXXXXXXX)
  sed "s^@PROJMD_BASE@^${PROJMD_BASE}^g" "${PROJMD_BASE}/cfg/dosbox_init.conf" > "${PROJMD_DBINIT}"
}
dosbox_deinit() {
  if [ -z "${PROJMD_DBINIT}" ]; then
    echo "Error: Calling dosbox_deinit with PROJMD_DEINIT undefined!" >&2
    exit 1
  fi
  rm -f "${PROJMD_DBINIT}"
  unset PROJMD_DBINIT
}

### Definition commands & their usage

## compile
usage_compile() {
  echo "${PMDNAME} compile: MODULE.MML [MODULE2.MML...]" >&2
}

do_compile() {
  if [ $# -lt 1 ]; then
    usage_compile
    exit 1
  fi

  dosbox_init

  for mmlfile do
    PROJMD_MMLFILE_FULLPATH="$(realpath "${mmlfile}")"
    # TODO realpath workspace path, see macOS problem interactively worked around earlier
    PROJMD_MMLFILE_WORKSPACE="${PROJMD_MMLFILE_FULLPATH##${PROJMD_BASE}/workspace/}"
    if [ "${PROJMD_MMLFILE_WORKSPACE}" == "${PROJMD_MMLFILE_FULLPATH}" ]; then
      echo "File '${PROJMD_MMLFILE_FULLPATH}' is not relative to workspace '$PROJMD_BASE/workspace', skipping..." >&2
      continue
    fi

    PROJMD_DBCMD=$(mktemp dosbox_cmd.conf.XXXXXXXX)
    sed "s^@PROJMD_MMLFILE_WORKSPACE@^${PROJMD_MMLFILE_WORKSPACE}^g" "${PROJMD_BASE}/cfg/dosbox_cmd.conf" > "${PROJMD_DBCMD}"

    "${DOSBOX}" -conf "${PROJMD_DBINIT}" -conf "${PROJMD_DBCMD}" -conf "${PROJMD_BASE}/cfg/dosbox_deinit.conf"

    cat "${PROJMD_BASE}/PMD/MC.LOG"
    rm -f "${PROJMD_BASE}/PMD/MC.LOG"
    rm -f "${PROJMD_DBCMD}"
    unset PROJMD_DBCMD
  done

  dosbox_deinit
}

## shell
do_shell() {
  dosbox_init

  unset SDL_VIDEODRIVER
  "${DOSBOX}" -userconf -conf "${PROJMD_DBINIT}"

  dosbox_deinit
}

### End definitions

do_${PMDCMD} "$@"

